import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { useGetPrompt } from '@/hooks/usePrompts';
import { useSession } from '@/auth/SessionProvider';
import { SpinnerFullPage } from '@/components/ui';
import { Banner, Divider } from '@telegram-apps/telegram-ui';
import { TelegramMainButton } from '../../../../components/TelegramMainButton';
import { Fragment } from 'react/jsx-runtime';

export const Route = createFileRoute('/content/$promptId/details/')({
  component: ContentDetails,
});

// Helper function to get display label for prompt type
const getTypeLabel = (
  type: 'images' | 'videos' | 'stickers' | 'gifs' | 'animated_stickers'
): string => {
  switch (type) {
    case 'images':
      return 'Image';
    case 'videos':
      return 'GIF';
    case 'stickers':
      return 'Sticker';
    case 'gifs':
      return 'GIF';
    case 'animated_stickers':
      return 'Animated Sticker';
    default:
      return type;
  }
};

function ContentDetails() {
  const { promptId } = Route.useParams();
  const navigate = useNavigate();
  const { session } = useSession();

  const { data: prompt, isLoading, error } = useGetPrompt(promptId, session);

  const handleContinue = () => {
    navigate({
      to: '/content/$promptId/select-nfts',
      params: { promptId },
    });
  };

  if (isLoading) {
    return <SpinnerFullPage text="Loading prompt details..." />;
  }

  if (error || !prompt) {
    return (
      <div className="mx-auto max-w-4xl p-4">
        <div className="flex items-center justify-center p-8">
          <div className="text-center">
            <div className="mb-4 text-4xl">⚠️</div>
            <h2 className="text-tg-text mb-2 text-xl font-bold">
              Failed to load prompt
            </h2>
            <p className="text-tg-hint mb-4">
              {error?.message || 'Prompt not found'}
            </p>
          </div>
        </div>
      </div>
    );
  }

  // Get all preview images
  const getPreviewImages = () => {
    if (prompt.stickers && prompt.stickers.length > 0) return prompt.stickers;
    if (prompt.gifs && prompt.gifs.length > 0) return prompt.gifs;
    if (prompt.images && prompt.images.length > 0) return prompt.images;
    if (prompt.videos && prompt.videos.length > 0) return prompt.videos;
    if (prompt.animatedStickers && prompt.animatedStickers.length > 0)
      return prompt.animatedStickers;
    return [];
  };

  const previewImages = getPreviewImages();

  return (
    <div className="mx-auto max-w-4xl p-2">
      <div className="">
        {/* Pack Header */}
        <div className="rounded-lg">
          <div className="relative rounded-lg p-2">
            <div className="flex w-full flex-col items-center">
              {/* Collection Info */}
              <div className="w-full">
                <div className="flex flex-col items-center">
                  <h1 className="text-2xl font-bold">
                    {prompt.name || 'Untitled Prompt'}
                  </h1>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Description */}
        {prompt.description && (
          <div className="p-6">
            <p className="text-tg-hint text-sm">{prompt.description}</p>
          </div>
        )}

        <Divider />

        {/* Content List */}
        {previewImages.length > 0 && (
          <div>
            <Banner
              header={
                <h2 className="text-tg-text text-lg">
                  Generations from other users
                </h2>
              }
              description={
                <div>
                  <p className="text-xs">
                    Example of{' '}
                    {getTypeLabel(
                      prompt.type as
                        | 'images'
                        | 'videos'
                        | 'stickers'
                        | 'gifs'
                        | 'animated_stickers'
                    ).toLowerCase()}{' '}
                    generated by other users.
                  </p>
                  <p className="text-tg-accent-text text-xs">
                    You will receive 1 personalized{' '}
                    {getTypeLabel(
                      prompt.type as
                        | 'images'
                        | 'videos'
                        | 'stickers'
                        | 'gifs'
                        | 'animated_stickers'
                    ).toLowerCase()}
                  </p>
                </div>
              }
              style={{
                backgroundColor: 'var(--tg-secondary-bg)',
              }}
            >
              <Fragment>
                <div className="grid grid-cols-3 gap-2 md:gap-4">
                  {previewImages.map((imageUrl, index) => (
                    <div
                      key={index}
                      className="bg-tg-hint/10 relative aspect-square overflow-hidden rounded-lg"
                    >
                      <img
                        src={imageUrl}
                        alt={`${prompt.name || 'Content'} ${index + 1}`}
                        className="h-full w-full object-cover"
                        loading="lazy"
                        decoding="async"
                      />
                    </div>
                  ))}
                </div>
              </Fragment>
            </Banner>
          </div>
        )}

        {/* Get Started Button */}
        <TelegramMainButton
          text={`Get ${getTypeLabel(prompt.type as 'images' | 'videos' | 'stickers' | 'gifs' | 'animated_stickers').toLowerCase()} with your PFP`}
          onClick={handleContinue}
          visible={true}
        />
      </div>
    </div>
  );
}
